# Generated by Django 2.1 on 2018-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('joindate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
